### PR TITLE
Fix `humility rendmp` support on Sidecar

### LINKED ISSUE #592: `rendmp` phase check should be usable on Sidecars
There is a check which requires SPD data to be present, which we will only have on sleds: https://github.com/oxidecomputer/humility/blob/master/cmd/rendmp/src/lib.rs#L1629-L1670

```
aaron@sam ~ $ pfexec humility rendmp --rail V0P8_TF2_VDD_CORE --phase-check
humility: attached to 483:3754:0039001D4741500920383733 via ST-Link V3
humility: restoring default configuration...
humility: done restoring default configuration...
humility rendmp failed: member missing from struct: gimlet_bufs
```

We should make that check optional on Sidecar.

### PR DESCRIPTION
**Pull request by mkeeter**
This is intended to fix #592

Right now, it works for the ISL68224 and the dual-output RAA229618, but fails for the single-output RAA229618.

```
Phase check for RAA229618 at 0x63
PHASE |    VOUT    |    IOUT    |    TEMP    | RAIL
------|------------|------------|------------|------------
 0    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 1    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 2    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 3    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 4    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 5    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 6    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 7    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 8    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 9    |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 10   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 11   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 12   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 13   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 14   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 15   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 16   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 17   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 18   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
 19   |     0.000V |     0.000A |   27.000°C | V0P8_TF2_VDD_CORE
```

(leaving as a draft until we resolve this)

### CODE REVIEW

**Comment by mkeeter** [comment]
The single output channel was a red herring.  The actual issue was that `restore_default_config` was called even if we hadn't reconfigured the chip, and it breaks if the chip has not been reconfigured.  I had tried doing a phase check while in A0, which failed (and called `restore_default_config`); when I then went to A2, the chip was unhappy.  When Eric moved the Sidecar to a different station (resetting it), everything worked.

I've pushed a fix to only call `restore_default_config` when we get to the point of reconfiguring the chip, then re-tested in the same way: a phase check in A0 fails (as expected), but subsequent checks in A2 now work.

File: cmd/rendmp/src/lib.rs [hunk 1]
```diff
@@ -1140,11 +1191,12 @@ fn get_pin_states(
...
 
     let regs: &'static [u16] = match dev {
-        SupportedDevice::ISL68224 => &[
+        SupportedDevice::ISL68224(..) => &[
             0x00BD, // open-pin
             0xE925, // mask
         ],
-        SupportedDevice::RAA229618 => &[
+        SupportedDevice::RAA229618(..) => &[
+            // XXX is this okay for both single and dual flavors?
```
Comment (Aaron-Hartwig) [inline cmd/rendmp/src/lib.rs]: Is this something you need us to get more information to answer? Or just a mark of uncertainty for future us?

File: cmd/rendmp/src/lib.rs [hunk 2]
```diff
@@ -952,46 +951,90 @@ fn rendmp_ingest(subargs: &RendmpArgs) -> Result<()> {
...
+            SupportedDevice::ISL68224(n) => {
                 let mut phases = vec![];
                 for phase in 0..6 {
                     phases.push((phase.to_string(), phase + 3));
                 }
-                for i in 0..3 {
-                    phases.push((format!("VSEN{i}"), i + 12));
+                for i in 0..*n {
+                    // TODO is this correct?
+                    phases.push((format!("VSEN{i}"), i as u32 + 12));
```
Comment (Aaron-Hartwig) [inline cmd/rendmp/src/lib.rs]: What is in question here? About the phase numbering for the part?

File: cmd/rendmp/src/lib.rs [hunk 3]
```diff
@@ -952,46 +951,90 @@ fn rendmp_ingest(subargs: &RendmpArgs) -> Result<()> {
...
+            SupportedDevice::RAA229618(n) => {
                 let mut phases = vec![];
                 for phase in 0..20 {
                     phases.push((phase.to_string(), phase));
                 }
-                for i in 0..2 {
-                    phases.push((format!("VSEN{i}"), i + 20));
+                for i in 0..*n {
+                    // TODO is this correct?
+                    phases.push((format!("VSEN{i}"), i as u32 + 20));
```
Comment (Aaron-Hartwig) [inline cmd/rendmp/src/lib.rs]: Same question as above.

**Review by Aaron-Hartwig — COMMENTED** [review]
I have questions about some comments and if/how we can answer them.

**Comment by mkeeter** [comment]
@Aaron-Hartwig all of those comments were suspicions from when I was investigating `V0P8_TF2_VDD_CORE`, so I've now deleted them all.

**Review by Aaron-Hartwig — APPROVED** [review]
Okay, great! I just wanted to be very sure if we needed to help track down any other unknowns. Thanks for extending things here!
